### ISSUE TITLE
Issue with `currentPage` variable in Sidebar

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.js.org#308]
Example: https://webpack.js.org/how-to/code-splitting/splitting-vendor/ . Notice the sidebar. This has likely something to do with the way it resolves the status.

**Comment by NejcZdovc** [comment]
I am testing this on the latest version from develop branch and it's working correctly.

**Comment by SpaceK33z** [comment]
Not sure, but looking at webpack.js.org (which was just deployed) it seems like this issue was fixed?

**Comment by skipjack** [comment]
Weird. It does look fixed, however yesterday when I was testing other stuff with `build-test` this was still broken.

**Comment by SpaceK33z** [comment]
Yeah I noticed that too, but I think @sokra fixed it in Antwar yesterday and updated the Antwar version this morning.

**Comment by skipjack** [comment]
awesome 👍
